version: '3.4'

services:
  postgres:
    container_name: sss-db
    image: postgis/postgis:15-3.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sss_admin_password
      - POSTGRES_USER=sss_admin
      - POSTGRES_DB=postgres
    networks:
      - sss-network
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    networks:
      - sss-network
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: unless-stopped

networks:
  sss-network: