INSERT INTO sss_meetings.countries VALUES ('AD', 'Andorra');
INSERT INTO sss_meetings.countries VALUES ('AE', 'United Arab Emirates');
INSERT INTO sss_meetings.countries VALUES ('AF', 'Afghanistan');
INSERT INTO sss_meetings.countries VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO sss_meetings.countries VALUES ('AI', 'Anguilla');
INSERT INTO sss_meetings.countries VALUES ('AL', 'Albania');
INSERT INTO sss_meetings.countries VALUES ('AM', 'Armenia');
INSERT INTO sss_meetings.countries VALUES ('AN', 'Netherlands Antilles');
INSERT INTO sss_meetings.countries VALUES ('AO', 'Angola');
INSERT INTO sss_meetings.countries VALUES ('AQ', 'Antarctica');
INSERT INTO sss_meetings.countries VALUES ('AR', 'Argentina');
INSERT INTO sss_meetings.countries VALUES ('AS', 'American Samoa');
INSERT INTO sss_meetings.countries VALUES ('AT', 'Austria');
INSERT INTO sss_meetings.countries VALUES ('AU', 'Australia');
INSERT INTO sss_meetings.countries VALUES ('AW', 'Aruba');
INSERT INTO sss_meetings.countries VALUES ('AX', 'Aland Islands');
INSERT INTO sss_meetings.countries VALUES ('AZ', 'Azerbaijan');
INSERT INTO sss_meetings.countries VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO sss_meetings.countries VALUES ('BB', 'Barbados');
INSERT INTO sss_meetings.countries VALUES ('BD', 'Bangladesh');
INSERT INTO sss_meetings.countries VALUES ('BE', 'Belgium');
INSERT INTO sss_meetings.countries VALUES ('BF', 'Burkina Faso');
INSERT INTO sss_meetings.countries VALUES ('BG', 'Bulgaria');
INSERT INTO sss_meetings.countries VALUES ('BH', 'Bahrain');
INSERT INTO sss_meetings.countries VALUES ('BI', 'Burundi');
INSERT INTO sss_meetings.countries VALUES ('BJ', 'Benin');
INSERT INTO sss_meetings.countries VALUES ('BM', 'Bermuda');
INSERT INTO sss_meetings.countries VALUES ('BN', 'Brunei Darussalam');
INSERT INTO sss_meetings.countries VALUES ('BO', 'Bolivia');
INSERT INTO sss_meetings.countries VALUES ('BR', 'Brazil');
INSERT INTO sss_meetings.countries VALUES ('BS', 'Bahamas');
INSERT INTO sss_meetings.countries VALUES ('BT', 'Bhutan');
INSERT INTO sss_meetings.countries VALUES ('BV', 'Bouvet Island');
INSERT INTO sss_meetings.countries VALUES ('BW', 'Botswana');
INSERT INTO sss_meetings.countries VALUES ('BY', 'Belarus');
INSERT INTO sss_meetings.countries VALUES ('BZ', 'Belize');
INSERT INTO sss_meetings.countries VALUES ('CA', 'Canada');
INSERT INTO sss_meetings.countries VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO sss_meetings.countries VALUES ('CD', 'Congo, The Democratic Republic of the');
INSERT INTO sss_meetings.countries VALUES ('CF', 'Central African Republic');
INSERT INTO sss_meetings.countries VALUES ('CG', 'Congo');
INSERT INTO sss_meetings.countries VALUES ('CH', 'Switzerland');
INSERT INTO sss_meetings.countries VALUES ('CI', 'Cote DIvoire');
INSERT INTO sss_meetings.countries VALUES ('CK', 'Cook Islands');
INSERT INTO sss_meetings.countries VALUES ('CL', 'Chile');
INSERT INTO sss_meetings.countries VALUES ('CM', 'Cameroon');
INSERT INTO sss_meetings.countries VALUES ('CN', 'China');
INSERT INTO sss_meetings.countries VALUES ('CO', 'Colombia');
INSERT INTO sss_meetings.countries VALUES ('CR', 'Costa Rica');
INSERT INTO sss_meetings.countries VALUES ('CU', 'Cuba');
INSERT INTO sss_meetings.countries VALUES ('CV', 'Cape Verde');
INSERT INTO sss_meetings.countries VALUES ('CX', 'Christmas Island');
INSERT INTO sss_meetings.countries VALUES ('CY', 'Cyprus');
INSERT INTO sss_meetings.countries VALUES ('CZ', 'Czech Republic');
INSERT INTO sss_meetings.countries VALUES ('DE', 'Germany');
INSERT INTO sss_meetings.countries VALUES ('DJ', 'Djibouti');
INSERT INTO sss_meetings.countries VALUES ('DK', 'Denmark');
INSERT INTO sss_meetings.countries VALUES ('DM', 'Dominica');
INSERT INTO sss_meetings.countries VALUES ('DO', 'Dominican Republic');
INSERT INTO sss_meetings.countries VALUES ('DZ', 'Algeria');
INSERT INTO sss_meetings.countries VALUES ('EC', 'Ecuador');
INSERT INTO sss_meetings.countries VALUES ('EE', 'Estonia');
INSERT INTO sss_meetings.countries VALUES ('EG', 'Egypt');
INSERT INTO sss_meetings.countries VALUES ('EH', 'Western Sahara');
INSERT INTO sss_meetings.countries VALUES ('ER', 'Eritrea');
INSERT INTO sss_meetings.countries VALUES ('ES', 'Spain');
INSERT INTO sss_meetings.countries VALUES ('ET', 'Ethiopia');
INSERT INTO sss_meetings.countries VALUES ('FI', 'Finland');
INSERT INTO sss_meetings.countries VALUES ('FJ', 'Fiji');
INSERT INTO sss_meetings.countries VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO sss_meetings.countries VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO sss_meetings.countries VALUES ('FO', 'Faroe Islands');
INSERT INTO sss_meetings.countries VALUES ('FR', 'France');
INSERT INTO sss_meetings.countries VALUES ('GA', 'Gabon');
INSERT INTO sss_meetings.countries VALUES ('GB', 'United Kingdom');
INSERT INTO sss_meetings.countries VALUES ('GD', 'Grenada');
INSERT INTO sss_meetings.countries VALUES ('GE', 'Georgia');
INSERT INTO sss_meetings.countries VALUES ('GF', 'French Guiana');
INSERT INTO sss_meetings.countries VALUES ('GG', 'Guernsey');
INSERT INTO sss_meetings.countries VALUES ('GH', 'Ghana');
INSERT INTO sss_meetings.countries VALUES ('GI', 'Gibraltar');
INSERT INTO sss_meetings.countries VALUES ('GL', 'Greenland');
INSERT INTO sss_meetings.countries VALUES ('GM', 'Gambia');
INSERT INTO sss_meetings.countries VALUES ('GN', 'Guinea');
INSERT INTO sss_meetings.countries VALUES ('GP', 'Guadeloupe');
INSERT INTO sss_meetings.countries VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO sss_meetings.countries VALUES ('GR', 'Greece');
INSERT INTO sss_meetings.countries VALUES ('GS', 'South Georgia and the South Sandwich Islands');
INSERT INTO sss_meetings.countries VALUES ('GT', 'Guatemala');
INSERT INTO sss_meetings.countries VALUES ('GU', 'Guam');
INSERT INTO sss_meetings.countries VALUES ('GW', 'Guinea-Bissau');
INSERT INTO sss_meetings.countries VALUES ('GY', 'Guyana');
INSERT INTO sss_meetings.countries VALUES ('HK', 'Hong Kong');
INSERT INTO sss_meetings.countries VALUES ('HM', 'Heard Island and Mcdonald Islands');
INSERT INTO sss_meetings.countries VALUES ('HN', 'Honduras');
INSERT INTO sss_meetings.countries VALUES ('HR', 'Croatia');
INSERT INTO sss_meetings.countries VALUES ('HT', 'Haiti');
INSERT INTO sss_meetings.countries VALUES ('HU', 'Hungary');
INSERT INTO sss_meetings.countries VALUES ('ID', 'Indonesia');
INSERT INTO sss_meetings.countries VALUES ('IE', 'Ireland');
INSERT INTO sss_meetings.countries VALUES ('IL', 'Israel');
INSERT INTO sss_meetings.countries VALUES ('IM', 'Isle of Man');
INSERT INTO sss_meetings.countries VALUES ('IN', 'India');
INSERT INTO sss_meetings.countries VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO sss_meetings.countries VALUES ('IQ', 'Iraq');
INSERT INTO sss_meetings.countries VALUES ('IR', 'Iran, Islamic Republic Of');
INSERT INTO sss_meetings.countries VALUES ('IS', 'Iceland');
INSERT INTO sss_meetings.countries VALUES ('IT', 'Italy');
INSERT INTO sss_meetings.countries VALUES ('JE', 'Jersey');
INSERT INTO sss_meetings.countries VALUES ('JM', 'Jamaica');
INSERT INTO sss_meetings.countries VALUES ('JO', 'Jordan');
INSERT INTO sss_meetings.countries VALUES ('JP', 'Japan');
INSERT INTO sss_meetings.countries VALUES ('KE', 'Kenya');
INSERT INTO sss_meetings.countries VALUES ('KG', 'Kyrgyzstan');
INSERT INTO sss_meetings.countries VALUES ('KH', 'Cambodia');
INSERT INTO sss_meetings.countries VALUES ('KI', 'Kiribati');
INSERT INTO sss_meetings.countries VALUES ('KM', 'Comoros');
INSERT INTO sss_meetings.countries VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO sss_meetings.countries VALUES ('KP', 'Korea, Democratic PeopleS Republic of');
INSERT INTO sss_meetings.countries VALUES ('KR', 'Korea, Republic of');
INSERT INTO sss_meetings.countries VALUES ('KW', 'Kuwait');
INSERT INTO sss_meetings.countries VALUES ('KY', 'Cayman Islands');
INSERT INTO sss_meetings.countries VALUES ('KZ', 'Kazakhstan');
INSERT INTO sss_meetings.countries VALUES ('LA', 'Lao PeopleS Democratic Republic');
INSERT INTO sss_meetings.countries VALUES ('LB', 'Lebanon');
INSERT INTO sss_meetings.countries VALUES ('LC', 'Saint Lucia');
INSERT INTO sss_meetings.countries VALUES ('LI', 'Liechtenstein');
INSERT INTO sss_meetings.countries VALUES ('LK', 'Sri Lanka');
INSERT INTO sss_meetings.countries VALUES ('LR', 'Liberia');
INSERT INTO sss_meetings.countries VALUES ('LS', 'Lesotho');
INSERT INTO sss_meetings.countries VALUES ('LT', 'Lithuania');
INSERT INTO sss_meetings.countries VALUES ('LU', 'Luxembourg');
INSERT INTO sss_meetings.countries VALUES ('LV', 'Latvia');
INSERT INTO sss_meetings.countries VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO sss_meetings.countries VALUES ('MA', 'Morocco');
INSERT INTO sss_meetings.countries VALUES ('MC', 'Monaco');
INSERT INTO sss_meetings.countries VALUES ('MD', 'Moldova, Republic of');
INSERT INTO sss_meetings.countries VALUES ('ME', 'Montenegro');
INSERT INTO sss_meetings.countries VALUES ('MG', 'Madagascar');
INSERT INTO sss_meetings.countries VALUES ('MH', 'Marshall Islands');
INSERT INTO sss_meetings.countries VALUES ('MK', 'Macedonia, The Former Yugoslav Republic of');
INSERT INTO sss_meetings.countries VALUES ('ML', 'Mali');
INSERT INTO sss_meetings.countries VALUES ('MM', 'Myanmar');
INSERT INTO sss_meetings.countries VALUES ('MN', 'Mongolia');
INSERT INTO sss_meetings.countries VALUES ('MO', 'Macao');
INSERT INTO sss_meetings.countries VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO sss_meetings.countries VALUES ('MQ', 'Martinique');
INSERT INTO sss_meetings.countries VALUES ('MR', 'Mauritania');
INSERT INTO sss_meetings.countries VALUES ('MS', 'Montserrat');
INSERT INTO sss_meetings.countries VALUES ('MT', 'Malta');
INSERT INTO sss_meetings.countries VALUES ('MU', 'Mauritius');
INSERT INTO sss_meetings.countries VALUES ('MV', 'Maldives');
INSERT INTO sss_meetings.countries VALUES ('MW', 'Malawi');
INSERT INTO sss_meetings.countries VALUES ('MX', 'Mexico');
INSERT INTO sss_meetings.countries VALUES ('MY', 'Malaysia');
INSERT INTO sss_meetings.countries VALUES ('MZ', 'Mozambique');
INSERT INTO sss_meetings.countries VALUES ('NA', 'Namibia');
INSERT INTO sss_meetings.countries VALUES ('NC', 'New Caledonia');
INSERT INTO sss_meetings.countries VALUES ('NE', 'Niger');
INSERT INTO sss_meetings.countries VALUES ('NF', 'Norfolk Island');
INSERT INTO sss_meetings.countries VALUES ('NG', 'Nigeria');
INSERT INTO sss_meetings.countries VALUES ('NI', 'Nicaragua');
INSERT INTO sss_meetings.countries VALUES ('NL', 'Netherlands');
INSERT INTO sss_meetings.countries VALUES ('NO', 'Norway');
INSERT INTO sss_meetings.countries VALUES ('NP', 'Nepal');
INSERT INTO sss_meetings.countries VALUES ('NR', 'Nauru');
INSERT INTO sss_meetings.countries VALUES ('NU', 'Niue');
INSERT INTO sss_meetings.countries VALUES ('NZ', 'New Zealand');
INSERT INTO sss_meetings.countries VALUES ('OM', 'Oman');
INSERT INTO sss_meetings.countries VALUES ('PA', 'Panama');
INSERT INTO sss_meetings.countries VALUES ('PE', 'Peru');
INSERT INTO sss_meetings.countries VALUES ('PF', 'French Polynesia');
INSERT INTO sss_meetings.countries VALUES ('PG', 'Papua New Guinea');
INSERT INTO sss_meetings.countries VALUES ('PH', 'Philippines');
INSERT INTO sss_meetings.countries VALUES ('PK', 'Pakistan');
INSERT INTO sss_meetings.countries VALUES ('PL', 'Poland');
INSERT INTO sss_meetings.countries VALUES ('PM', 'Saint Pierre and Miquelon');
INSERT INTO sss_meetings.countries VALUES ('PN', 'Pitcairn');
INSERT INTO sss_meetings.countries VALUES ('PR', 'Puerto Rico');
INSERT INTO sss_meetings.countries VALUES ('PS', 'Palestinian Territory, Occupied');
INSERT INTO sss_meetings.countries VALUES ('PT', 'Portugal');
INSERT INTO sss_meetings.countries VALUES ('PW', 'Palau');
INSERT INTO sss_meetings.countries VALUES ('PY', 'Paraguay');
INSERT INTO sss_meetings.countries VALUES ('QA', 'Qatar');
INSERT INTO sss_meetings.countries VALUES ('RE', 'Reunion');
INSERT INTO sss_meetings.countries VALUES ('RO', 'Romania');
INSERT INTO sss_meetings.countries VALUES ('RS', 'Serbia');
INSERT INTO sss_meetings.countries VALUES ('RU', 'Russian Federation');
INSERT INTO sss_meetings.countries VALUES ('RW', 'RWANDA');
INSERT INTO sss_meetings.countries VALUES ('SA', 'Saudi Arabia');
INSERT INTO sss_meetings.countries VALUES ('SB', 'Solomon Islands');
INSERT INTO sss_meetings.countries VALUES ('SC', 'Seychelles');
INSERT INTO sss_meetings.countries VALUES ('SD', 'Sudan');
INSERT INTO sss_meetings.countries VALUES ('SE', 'Sweden');
INSERT INTO sss_meetings.countries VALUES ('SG', 'Singapore');
INSERT INTO sss_meetings.countries VALUES ('SH', 'Saint Helena');
INSERT INTO sss_meetings.countries VALUES ('SI', 'Slovenia');
INSERT INTO sss_meetings.countries VALUES ('SJ', 'Svalbard and Jan Mayen');
INSERT INTO sss_meetings.countries VALUES ('SK', 'Slovakia');
INSERT INTO sss_meetings.countries VALUES ('SL', 'Sierra Leone');
INSERT INTO sss_meetings.countries VALUES ('SM', 'San Marino');
INSERT INTO sss_meetings.countries VALUES ('SN', 'Senegal');
INSERT INTO sss_meetings.countries VALUES ('SO', 'Somalia');
INSERT INTO sss_meetings.countries VALUES ('SR', 'Suriname');
INSERT INTO sss_meetings.countries VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO sss_meetings.countries VALUES ('SV', 'El Salvador');
INSERT INTO sss_meetings.countries VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO sss_meetings.countries VALUES ('SZ', 'Swaziland');
INSERT INTO sss_meetings.countries VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO sss_meetings.countries VALUES ('TD', 'Chad');
INSERT INTO sss_meetings.countries VALUES ('TF', 'French Southern Territories');
INSERT INTO sss_meetings.countries VALUES ('TG', 'Togo');
INSERT INTO sss_meetings.countries VALUES ('TH', 'Thailand');
INSERT INTO sss_meetings.countries VALUES ('TJ', 'Tajikistan');
INSERT INTO sss_meetings.countries VALUES ('TK', 'Tokelau');
INSERT INTO sss_meetings.countries VALUES ('TL', 'Timor-Leste');
INSERT INTO sss_meetings.countries VALUES ('TM', 'Turkmenistan');
INSERT INTO sss_meetings.countries VALUES ('TN', 'Tunisia');
INSERT INTO sss_meetings.countries VALUES ('TO', 'Tonga');
INSERT INTO sss_meetings.countries VALUES ('TR', 'Turkey');
INSERT INTO sss_meetings.countries VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO sss_meetings.countries VALUES ('TV', 'Tuvalu');
INSERT INTO sss_meetings.countries VALUES ('TW', 'Taiwan, Province of China');
INSERT INTO sss_meetings.countries VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO sss_meetings.countries VALUES ('UA', 'Ukraine');
INSERT INTO sss_meetings.countries VALUES ('UG', 'Uganda');
INSERT INTO sss_meetings.countries VALUES ('UM', 'United States Minor Outlying Islands');
INSERT INTO sss_meetings.countries VALUES ('US', 'United States');
INSERT INTO sss_meetings.countries VALUES ('UY', 'Uruguay');
INSERT INTO sss_meetings.countries VALUES ('UZ', 'Uzbekistan');
INSERT INTO sss_meetings.countries VALUES ('VA', 'Holy See (Vatican City State)');
INSERT INTO sss_meetings.countries VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO sss_meetings.countries VALUES ('VE', 'Venezuela');
INSERT INTO sss_meetings.countries VALUES ('VG', 'Virgin Islands, British');
INSERT INTO sss_meetings.countries VALUES ('VI', 'Virgin Islands, U.S.');
INSERT INTO sss_meetings.countries VALUES ('VN', 'Viet Nam');
INSERT INTO sss_meetings.countries VALUES ('VU', 'Vanuatu');
INSERT INTO sss_meetings.countries VALUES ('WF', 'Wallis and Futuna');
INSERT INTO sss_meetings.countries VALUES ('WS', 'Samoa');
INSERT INTO sss_meetings.countries VALUES ('YE', 'Yemen');
INSERT INTO sss_meetings.countries VALUES ('YT', 'Mayotte');
INSERT INTO sss_meetings.countries VALUES ('ZA', 'South Africa');
INSERT INTO sss_meetings.countries VALUES ('ZM', 'Zambia');
INSERT INTO sss_meetings.countries VALUES ('ZW', 'Zimbabwe');